// This file is generated by scripts/generate-handbook.mjs.
// Do not edit directly; edit src/content/handbook/*.md instead.

export interface HandbookEditor {
  name: string;
  email: string;
  date: string;
  githubUsername?: string;
  githubUrl?: string;
  avatarUrl?: string;
}

export interface HandbookAuthor {
  name: string;
  githubUsername: string;
  githubUrl: string;
  avatarUrl: string;
}

export interface HandbookPage {
  slug: string;
  title: string;
  description: string;
  order: number;
  items: { title: string; slug: string; level: number }[];
  authors: HandbookAuthor[];
  body: string;
  sourcePath: string;
  lastEditor: HandbookEditor;
}

export const HANDBOOK_PAGES = [
  {
    "slug": "company",
    "title": "Company",
    "description": "Company handbook section.",
    "order": 10,
    "items": [
      {
        "title": "Introduction",
        "slug": "introduction",
        "level": 2
      },
      {
        "title": "Mission & Values",
        "slug": "mission-and-values",
        "level": 2
      },
      {
        "title": "Our Story",
        "slug": "our-story",
        "level": 2
      }
    ],
    "authors": [
      {
        "name": "Bryan Houlton",
        "githubUsername": "bryanhoulton",
        "githubUrl": "https://github.com/bryanhoulton",
        "avatarUrl": "https://avatars.githubusercontent.com/u/44454017?v=4"
      }
    ],
    "body": "## Introduction\n\n## Mission & Values\n\n## Our Story",
    "sourcePath": "src/content/handbook/company.md",
    "lastEditor": {
      "name": "Bryan Houlton",
      "email": "brhoulton@gmail.com",
      "date": "",
      "githubUsername": "bryanhoulton",
      "githubUrl": "https://github.com/bryanhoulton",
      "avatarUrl": "https://github.com/bryanhoulton.png?size=96"
    }
  },
  {
    "slug": "how-we-work",
    "title": "How We Work",
    "description": "Operating practices handbook section.",
    "order": 20,
    "items": [
      {
        "title": "Communication",
        "slug": "communication",
        "level": 2
      },
      {
        "title": "Meetings",
        "slug": "meetings",
        "level": 2
      },
      {
        "title": "Decision Making",
        "slug": "decision-making",
        "level": 2
      },
      {
        "title": "Remote Work",
        "slug": "remote-work",
        "level": 2
      }
    ],
    "authors": [
      {
        "name": "Bryan Houlton",
        "githubUsername": "bryanhoulton",
        "githubUrl": "https://github.com/bryanhoulton",
        "avatarUrl": "https://avatars.githubusercontent.com/u/44454017?v=4"
      }
    ],
    "body": "## Communication\n\n## Meetings\n\n## Decision Making\n\n## Remote Work",
    "sourcePath": "src/content/handbook/how-we-work.md",
    "lastEditor": {
      "name": "Bryan Houlton",
      "email": "brhoulton@gmail.com",
      "date": "",
      "githubUsername": "bryanhoulton",
      "githubUrl": "https://github.com/bryanhoulton",
      "avatarUrl": "https://github.com/bryanhoulton.png?size=96"
    }
  },
  {
    "slug": "people",
    "title": "People",
    "description": "People, compensation, and benefits handbook section.",
    "order": 30,
    "items": [
      {
        "title": "Compensation",
        "slug": "compensation",
        "level": 2
      },
      {
        "title": "Benefits",
        "slug": "benefits",
        "level": 2
      },
      {
        "title": "Time Off",
        "slug": "time-off",
        "level": 2
      },
      {
        "title": "Career Development",
        "slug": "career-development",
        "level": 2
      }
    ],
    "authors": [
      {
        "name": "Bryan Houlton",
        "githubUsername": "bryanhoulton",
        "githubUrl": "https://github.com/bryanhoulton",
        "avatarUrl": "https://avatars.githubusercontent.com/u/44454017?v=4"
      }
    ],
    "body": "## Compensation\n\n## Benefits\n\n## Time Off\n\n## Career Development",
    "sourcePath": "src/content/handbook/people.md",
    "lastEditor": {
      "name": "Bryan Houlton",
      "email": "brhoulton@gmail.com",
      "date": "",
      "githubUsername": "bryanhoulton",
      "githubUrl": "https://github.com/bryanhoulton",
      "avatarUrl": "https://github.com/bryanhoulton.png?size=96"
    }
  },
  {
    "slug": "policies",
    "title": "Policies",
    "description": "Company policy handbook section.",
    "order": 40,
    "items": [
      {
        "title": "Code of Conduct",
        "slug": "code-of-conduct",
        "level": 2
      },
      {
        "title": "Security",
        "slug": "security",
        "level": 2
      },
      {
        "title": "Expenses",
        "slug": "expenses",
        "level": 2
      }
    ],
    "authors": [
      {
        "name": "Bryan Houlton",
        "githubUsername": "bryanhoulton",
        "githubUrl": "https://github.com/bryanhoulton",
        "avatarUrl": "https://avatars.githubusercontent.com/u/44454017?v=4"
      }
    ],
    "body": "## Code of Conduct\n\n## Security\n\n## Expenses",
    "sourcePath": "src/content/handbook/policies.md",
    "lastEditor": {
      "name": "Bryan Houlton",
      "email": "brhoulton@gmail.com",
      "date": "",
      "githubUsername": "bryanhoulton",
      "githubUrl": "https://github.com/bryanhoulton",
      "avatarUrl": "https://github.com/bryanhoulton.png?size=96"
    }
  }
] satisfies HandbookPage[];
