// This file is generated by scripts/generate-handbook.mjs.
// Do not edit directly; edit src/content/handbook/*.md instead.

export interface HandbookEditor {
  name: string;
  email: string;
  date: string;
  githubUsername?: string;
  githubUrl?: string;
  avatarUrl?: string;
}

export interface HandbookAuthor {
  name: string;
  githubUsername: string;
  githubUrl: string;
  avatarUrl: string;
}

export interface HandbookPage {
  slug: string;
  title: string;
  description: string;
  order: number;
  items: { title: string; slug: string; level: number }[];
  authors: HandbookAuthor[];
  body: string;
  sourcePath: string;
  lastEditor: HandbookEditor;
}

export const HANDBOOK_PAGES = [
  {
    "slug": "company",
    "title": "Company",
    "description": "Company handbook section.",
    "order": 10,
    "items": [
      {
        "title": "Mission",
        "slug": "mission",
        "level": 3
      },
      {
        "title": "Culture",
        "slug": "culture",
        "level": 3
      }
    ],
    "authors": [
      {
        "name": "Bryan Houlton",
        "githubUsername": "bryanhoulton",
        "githubUrl": "https://github.com/bryanhoulton",
        "avatarUrl": "https://avatars.githubusercontent.com/u/44454017?v=4"
      }
    ],
    "body": "### Mission\n\nOur mission is to bring the AI takeoff to the physical world. AI can build software; we believe it should also be able to build physical infrastructure. To do this, we’re training AI to fully manage construction and infrastructure projects.\n\n### Culture\n\nWe are building a team of intentional people who could go work anywhere else, but are choosing to work on this mission. We take our work here seriously, show up on time, hold each other to a high bar, take feedback quickly, and think from first principles. We work extremely hard but love learning, find art and creativity in everything we can, and have a ton of fun.\n\nWe believe that building this culture requires an in-person team, and expect members to be fully in-person roughly by EOY. In the meantime, we’d want to have at least one week per month in person as a team and can facilitate this between DC and SF.",
    "sourcePath": "src/content/handbook/company.md",
    "lastEditor": {
      "name": "Bryan Houlton",
      "email": "brhoulton@gmail.com",
      "date": "2026-06-22T22:37:28-07:00"
    }
  },
  {
    "slug": "how-we-work",
    "title": "How We Work",
    "description": "Operating practices handbook section.",
    "order": 20,
    "items": [
      {
        "title": "Communication",
        "slug": "communication",
        "level": 2
      },
      {
        "title": "Writing Over Meetings",
        "slug": "writing-over-meetings",
        "level": 2
      },
      {
        "title": "Meetings",
        "slug": "meetings",
        "level": 2
      },
      {
        "title": "Decision Making",
        "slug": "decision-making",
        "level": 2
      },
      {
        "title": "Remote Work",
        "slug": "remote-work",
        "level": 2
      }
    ],
    "authors": [
      {
        "name": "Bryan Houlton",
        "githubUsername": "bryanhoulton",
        "githubUrl": "https://github.com/bryanhoulton",
        "avatarUrl": "https://avatars.githubusercontent.com/u/44454017?v=4"
      }
    ],
    "body": "## Communication\n\n## Writing Over Meetings\n\nWe prefer writing over meetings. If a meeting seems pointless or could be handled in writing, call it out.\n\n## Meetings\n\n## Decision Making\n\n## Remote Work",
    "sourcePath": "src/content/handbook/how-we-work.md",
    "lastEditor": {
      "name": "Bryan Houlton",
      "email": "brhoulton@gmail.com",
      "date": "2026-06-22T22:37:28-07:00"
    }
  },
  {
    "slug": "policies",
    "title": "Policies",
    "description": "Company policy handbook section.",
    "order": 40,
    "items": [
      {
        "title": "Code of Conduct",
        "slug": "code-of-conduct",
        "level": 2
      },
      {
        "title": "Security",
        "slug": "security",
        "level": 2
      },
      {
        "title": "No AI-Written Content",
        "slug": "no-ai-written-content",
        "level": 2
      },
      {
        "title": "Expenses",
        "slug": "expenses",
        "level": 2
      }
    ],
    "authors": [
      {
        "name": "Bryan Houlton",
        "githubUsername": "bryanhoulton",
        "githubUrl": "https://github.com/bryanhoulton",
        "avatarUrl": "https://avatars.githubusercontent.com/u/44454017?v=4"
      }
    ],
    "body": "## Code of Conduct\n\n## Security\n\n## No AI-Written Content\n\nDo not use AI to write. Draft and edit directly so the words reflect what we actually mean and how we actually operate.\n\n## Expenses",
    "sourcePath": "src/content/handbook/policies.md",
    "lastEditor": {
      "name": "Bryan Houlton",
      "email": "brhoulton@gmail.com",
      "date": "2026-06-22T22:37:28-07:00"
    }
  }
] satisfies HandbookPage[];
